### ISSUE TITLE
Функционал

### ISSUE THREAD

**Issue by daniilv-me** [kiriharu/morgenpost#4]
Могу предложить добавить курсы от Яндекс Деньги(RUB-EUR, RUB-USD), BTC, LiteCoin, Dash.
Также можно оформить бота, который будет предоставлять актуальный курс Рубля к Евро от Киви, ЦБ, Яндекс Деньги при нажатии кнопочки.

**Comment by kiriharu** [comment]
Уже есть курсы валют на блокчейне, кто-то запилил. 
По поводу кнопочек - это не того формата бот. Он просто отсылает текст каждое утро с необходимой информацией.
